version: '3.8'

services:
  backend:
    build:
      context: ./  # Set the build context to the root of the project
      dockerfile: ./server/Dockerfile  # Path to the backend Dockerfile
    container_name: backend
    ports:
      - "5050:5050"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern-app
    depends_on:
      - mongo
    networks:
      - mern-network
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-network
    restart: always

  frontend:
    build:
      context: ./  # Set the context to the frontend folder
      dockerfile: ./client/Dockerfile  # Path to the frontend Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mern-network
    restart: always

networks:
  mern-network:
    driver: bridge
