version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-network

  backend:
    build: ./server
    container_name: backend
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:example@mongo:27017
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app
    ports:
      - "5000:5000"
    networks:
      - mern-network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    networks:
      - mern-network

volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge


